name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  generate-ref:
    name: Generate Ref
    runs-on: ubuntu-latest
    outputs:
      REF: ${{ steps.generate-ref.outputs.ref }}
    steps:
      - run: helm version
      - uses: actions/checkout@v7
      - run: helm version
      - id: generate-ref
        name: Generate Ref
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ] ; then
            ref=$(php -r "echo str_replace('/', '-SLASH-', '${{ github.event.pull_request.head.ref }}');")
            echo "$ref"
            echo "ref=$ref" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "${GITHUB_REF##*/}"
          echo "ref=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
  runner-matrix:
    name: Runner Matrix
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.runner-matrix.outputs.runner }}
    steps:
      - id: runner-matrix
        name: Runner Matrix
        run: |
          echo 'runner=["ubuntu-latest"]' >> $GITHUB_OUTPUT
  tests-helm-works:
    name: "Testing Helm Command: ${{ matrix.exec }} on ${{ matrix.runner }}"
    runs-on: ${{ matrix.runner }}
    needs:
      - runner-matrix
    strategy:
      matrix:
        runner: ${{ fromJson(needs.runner-matrix.outputs.runner) }}
        exec:
          - "helm version"
          - "helm repo add podinfo https://stefanprodan.github.io/podinfo"
          - "helm repo add podinfo https://stefanprodan.github.io/podinfo && helm repo list"
          - "helm plugin install https://github.com/hypnoglow/helm-s3.git"
          - "helm plugin install https://github.com/hypnoglow/helm-s3.git && helm plugin list"
          - "helm env"
    steps:
      - uses: actions/checkout@v7
      - uses: ./
        with:
          exec: ${{ matrix.exec }}
          kubeconfig: tada
  tests-helm-output:
    name: "Testing Helm Output ${{ matrix.runner }}"
    runs-on: ${{ matrix.runner }}
    needs:
      - runner-matrix
    strategy:
      matrix:
        runner: ${{ fromJson(needs.runner-matrix.outputs.runner) }}
    steps:
      - uses: actions/checkout@v7
      - run: helm version
      - uses: ./
        id: helm3
        with:
          exec: helm repo add podinfo https://stefanprodan.github.io/podinfo && helm repo list
          kubeconfig: tada
      - run: |
          php -r "exit(strpos('${HELM_OUTPUT}', 'podinfo') !== false ? 0 : 255);"
        env:
          HELM_OUTPUT: ${{ steps.helm3.outputs.helm_output }}
      - run: |
          php -r "exit(strpos('${HELM_OUTPUT}', 'has been added to your repositories') !== false ? 0 : 255);"
        env:
          HELM_OUTPUT: ${{ steps.helm3.outputs.helm_output }}
      - run: |
          php -r "exit(strpos('${HELM_OUTPUT}', 'https://stefanprodan.github.io/podinfo') !== false ? 0 : 255);"
        env:
          HELM_OUTPUT: ${{ steps.helm3.outputs.helm_output }}
  tests-helm-install-input:
    name: "Testing Helm Install (input) ${{ matrix.runner }}"
    runs-on: ${{ matrix.runner }}
    needs:
      - runner-matrix
    strategy:
      matrix:
        runner: ${{ fromJson(needs.runner-matrix.outputs.runner) }}
    steps:
      - uses: actions/checkout@v7
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - name: Get running image ID
        id: ps
        run: echo "id=$(docker ps --format '{{.ID}}')" >> $GITHUB_OUTPUT
        env:
          IMAGE: ${{ steps.build.outputs.tag }}
      - name: Get running image IP
        id: inspect
        run: echo "ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${IMAGE_ID})" >> $GITHUB_OUTPUT
        env:
          IMAGE_ID: ${{ steps.ps.outputs.id }}
      - run: sed -i "s/127.0.0.1:32768/${KIND_IP}:6443/g" ~/.kube/config
        env:
          KIND_IP: ${{ steps.inspect.outputs.ip }}
      - name: Make kubeconfig available to Helm3 action
        run: |
          kubeconfig=$(cat ~/.kube/config)
          kubeconfig="${kubeconfig//'%'/'%25'}"
          kubeconfig="${kubeconfig//$'\n'/'%0A'}"
          kubeconfig="${kubeconfig//$'\r'/'%0D'}"
          echo "kubeconfig=$kubeconfig" >> $GITHUB_OUTPUT
        id: kubeconfig
      - name: List installed packages
        uses: ./
        id: helmlistcountfirst
        with:
          exec: |
            printf "count=%s\n" $(helm list | grep podinfo | wc -l) >> $GITHUB_OUTPUT
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - run: |
          php -r "exit(trim('${COUNT}') === '0' ? 0 : 255);"
        env:
          COUNT: ${{ steps.helmlistcountfirst.outputs.count }}
      - name: Install podinfo
        uses: ./
        id: helm3
        with:
          exec: |
            helm repo add podinfo https://stefanprodan.github.io/podinfo
            helm install podinfo podinfo/podinfo --atomic
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - name: List installed packages
        uses: ./
        with:
          exec: |
            helm list
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - name: List installed packages
        uses: ./
        id: helmlistcountseccond
        with:
          exec: |
            helm list
            printf "count=%s\n" $(helm list | grep podinfo | wc -l) >> $GITHUB_OUTPUT
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - run: |
          php -r "exit(trim('${COUNT}') === '1' ? 0 : 255);"
        env:
          COUNT: ${{ steps.helmlistcountseccond.outputs.count }}
      - name: UnInstall podinfo
        uses: ./
        with:
          exec: |
            helm uninstall podinfo
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - name: List installed packages
        uses: ./
        id: helmlistcountthird
        with:
          exec: |
            helm list
            printf "count=%s\n" $(helm list | grep podinfo | wc -l) >> $GITHUB_OUTPUT
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - run: |
          php -r "exit(trim('${COUNT}') === '0' ? 0 : 255);"
        env:
          COUNT: ${{ steps.helmlistcountthird.outputs.count }}
  tests-helm-install-input-overruled:
    name: "Testing Helm Install (input overruled) ${{ matrix.runner }}"
    runs-on: ${{ matrix.runner }}
    needs:
      - runner-matrix
    strategy:
      matrix:
        runner: ${{ fromJson(needs.runner-matrix.outputs.runner) }}
    steps:
      - uses: actions/checkout@v7
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - name: Get running image ID
        id: ps
        run: echo "id=$(docker ps --format '{{.ID}}')" >> $GITHUB_OUTPUT
        env:
          IMAGE: ${{ steps.build.outputs.tag }}
      - name: Get running image IP
        id: inspect
        run: echo "ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${IMAGE_ID})" >> $GITHUB_OUTPUT
        env:
          IMAGE_ID: ${{ steps.ps.outputs.id }}
      - run: sed -i "s/127.0.0.1:32768/${KIND_IP}:6443/g" ~/.kube/config
        env:
          KIND_IP: ${{ steps.inspect.outputs.ip }}
      - name: Make kubeconfig available to Helm3 action
        run: |
          kubeconfig=$(cat ~/.kube/config)
          kubeconfig="${kubeconfig//'%'/'%25'}"
          kubeconfig="${kubeconfig//$'\n'/'%0A'}"
          kubeconfig="${kubeconfig//$'\r'/'%0D'}"
          echo "kubeconfig=$kubeconfig" >> $GITHUB_OUTPUT
        id: kubeconfig
      - name: List installed packages
        uses: ./
        id: helmlistcountfirst
        with:
          exec: |
            printf "count=%s\n" $(helm list | grep podinfo | wc -l) >> $GITHUB_OUTPUT
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - run: |
          php -r "exit(trim('${COUNT}') === '0' ? 0 : 255);"
        env:
          COUNT: ${{ steps.helmlistcountfirst.outputs.count }}
      - name: Install podinfo
        uses: ./
        id: helm3
        with:
          exec: |
            helm repo add podinfo https://stefanprodan.github.io/podinfo
            helm install podinfo podinfo/podinfo --atomic
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - name: List installed packages
        uses: ./
        with:
          exec: |
            helm list
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - run: |
          rm ~/.kube -Rf
          mkdir ~/.kube
          echo "junk" > ~/.kube/config
      - name: Get kubeconfig contents
        uses: ./
        id: getkubeconfigcontents
        with:
          exec: |
            helm list
            printf "cnt=%s\n" $(cat ~/.kube/config) >> $GITHUB_OUTPUT
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - name: "Assert kubeconfig really contains: junk"
        uses: nick-fields/assert-action@v4
        with:
          expected: junk
          actual: ${{ steps.getkubeconfigcontents.outputs.cnt }}
      - name: List installed packages through a overruled kubeconfig
        uses: ./
        id: helmlistcountoverruledkubeconfig
        with:
          exec: |
            helm list
            printf "count=%s\n" $(helm list | grep podinfo | wc -l) >> $GITHUB_OUTPUT
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
          overrule_existing_kubeconfig: "true"
      - run: |
          php -r "exit(trim('${COUNT}') === '1' ? 0 : 255);"
        env:
          COUNT: ${{ steps.helmlistcountoverruledkubeconfig.outputs.count }}
      - run: |
          rm ~/.kube -Rf
      - name: UnInstall podinfo
        uses: ./
        with:
          exec: |
            helm uninstall podinfo
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - name: List installed packages
        uses: ./
        id: helmlistcountthird
        with:
          exec: |
            helm list
            printf "count=%s\n" $(helm list | grep podinfo | wc -l) >> $GITHUB_OUTPUT
          kubeconfig: ${{ steps.kubeconfig.outputs.kubeconfig }}
      - run: |
          php -r "exit(trim('${COUNT}') === '0' ? 0 : 255);"
        env:
          COUNT: ${{ steps.helmlistcountthird.outputs.count }}
  tests-helm-install-file:
    name: "Testing Helm Install (file) ${{ matrix.runner }}"
    runs-on: ${{ matrix.runner }}
    needs:
      - runner-matrix
    strategy:
      matrix:
        runner: ${{ fromJson(needs.runner-matrix.outputs.runner) }}
    steps:
      - uses: actions/checkout@v7
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - name: Get running image ID
        id: ps
        run: echo "id=$(docker ps --format '{{.ID}}')" >> $GITHUB_OUTPUT
        env:
          IMAGE: ${{ steps.build.outputs.tag }}
      - name: Get running image IP
        id: inspect
        run: echo "ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${IMAGE_ID})" >> $GITHUB_OUTPUT
        env:
          IMAGE_ID: ${{ steps.ps.outputs.id }}
      - run: sed -i "s/127.0.0.1:32768/${KIND_IP}:6443/g" ~/.kube/config
        env:
          KIND_IP: ${{ steps.inspect.outputs.ip }}
      - name: List installed packages
        uses: ./
        id: helmlistcountfirst
        with:
          exec: |
            helm list | grep podinfo | wc -l
      - run: |
          php -r "exit(trim('${COUNT}') === '0' ? 0 : 255);"
        env:
          COUNT: ${{ steps.helmlistcountfirst.outputs.helm_output }}
      - name: Install podinfo
        uses: ./
        id: helm3
        with:
          exec: |
            helm repo add podinfo https://stefanprodan.github.io/podinfo
            helm install podinfo podinfo/podinfo --atomic
      - name: List installed packages
        uses: ./
        with:
          exec: |
            helm list
      - name: List installed packages
        uses: ./
        id: helmlistcountseccond
        with:
          exec: |
            helm list | grep podinfo | wc -l
      - run: |
          php -r "exit(trim('${COUNT}') === '1' ? 0 : 255);"
        env:
          COUNT: ${{ steps.helmlistcountseccond.outputs.helm_output }}
      - name: UnInstall podinfo
        uses: ./
        with:
          exec: |
            helm uninstall podinfo
      - name: List installed packages
        uses: ./
        id: helmlistcountthird
        with:
          exec: |
            helm list | grep podinfo | wc -l
      - run: |
          php -r "exit(trim('${COUNT}') === '0' ? 0 : 255);"
        env:
          COUNT: ${{ steps.helmlistcountthird.outputs.helm_output }}

